version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: test-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
  
  kafka:
    image: wurstmeister/kafka
    container_name: test-kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "test:1:1"
    depends_on:
      - zookeeper