version: '3.1'

services:
  zookeeper:
    image: zookeeper
    container_name: test-zookeeper
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
  
  kafka1:
    image: wurstmeister/kafka
    container_name: test-kafka1
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 1
      KAFKA_CREATE_TOPICS: "crawler-BTC:1:1"
    depends_on:
      - zookeeper

  kafka2:
    image: wurstmeister/kafka
    container_name: test-kafka2
    ports:
      - 9093:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9093
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 2
      KAFKA_CREATE_TOPICS: "crawler-ETH:1:1"
    depends_on:
      - zookeeper
  
  kafka3:
    image: wurstmeister/kafka
    container_name: test-kafka3
    ports:
      - 9094:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9094
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 3
      KAFKA_CREATE_TOPICS: "crawler-XRP:1:1"
    depends_on:
      - zookeeper
  
  kafka4:
    image: wurstmeister/kafka
    container_name: test-kafka4
    ports:
      - 9095:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: 192.168.99.100
      KAFKA_ADVERTISED_PORT: 9095
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_BROKER_ID: 4
      KAFKA_CREATE_TOPICS: "crawler-EOS:1:1"
    depends_on:
      - zookeeper